apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote-app
  template:
    metadata:
      labels:
        app: knote-app
    spec:
      containers:
        - name: knote
          image: keicee32/knote-image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: 'mongodb://10.103.198.120:27017/dev'

