apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - name: my-volume
              mountPath: /data/db
          ports:
            - containerPort: 27017
      volumes:
        - name: my-volume
          emptyDir: {}
